language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

notifications:
  email:
    - yoav@yoavram.com

install:
  - pip install click
  - python setup.py install

script: py.test

